# Generated by Django 5.1.3 on 2024-11-19 09:17

import sportNews.custom_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportNews', '0004_feed_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.AlterField(
            model_name='article',
            name='special',
            field=sportNews.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='list', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=sportNews.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='list', max_length=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='list', max_length=10),
        ),
    ]
